name: markscribe

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  markscribe:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          LITERAL_EMAIL: ${{ secrets.LITERAL_EMAIL }}
          LITERAL_PASSWORD: ${{ secrets.LITERAL_PASSWORD }}
        with:
          template: "templates/README.gtpl"
          writeTo: "README.md"

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Set random string & Pacman
        id: random
        run: echo "value=$(date +%s | sha256sum | base64 | head -c 8)" >> $GITHUB_OUTPUT

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: "docs: Update generated README ${{ steps.random.outputs.value }}"
          branch: master
          commit_user_name: leonardorifeli
          commit_user_email: leonardorifeli@gmail.com
          commit_author: Leonardo Rifeli <leonardorifeli@gmail.com>
