name: markscribe

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  markscribe:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          LITERAL_EMAIL: ${{ secrets.LITERAL_EMAIL }}
          LITERAL_PASSWORD: ${{ secrets.LITERAL_PASSWORD }}
        with:
          template: "templates/README.gtpl"
          writeTo: "README.md"
      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: 'docs: Update generated README'
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>