name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - run: |
          go install github.com/muesli/markscribe@master
          markscribe -write ./templates/readme.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          LITERAL_EMAIL: ${{ secrets.LITERAL_EMAIL }}
          LITERAL_PASSWORD: ${{ secrets.LITERAL_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          commit_message: 'docs: Update generated README'
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>