name: Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: |
          go install github.com/muesli/markscribe@master
          markscribe ./templates/readme.md.tpl > README.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          LITERAL_EMAIL: ${{ secrets.LITERAL_EMAIL }}
          LITERAL_PASSWORD: ${{ secrets.LITERAL_PASSWORD }}
